apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: secret-sidecar
  labels:
    app: myapp
spec:
  serviceAccountName: secret-sidecar-sa
  volumes:
    - name: vol
      emptyDir:
        medium: Memory
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo $(cat /tmp/secret) && sleep 3600']
    volumeMounts:
      - name: vol
        mountPath: /tmp
  initContainers:
  - name: secrets-manager
    image: acrasgardeomainrnd001.azurecr.io/secret-sidecar:latest
    env:
      - name: AZURE_VAULT_NAME
        value: "secretsidecar"
      - name: AZURE_SECRET_NAME
        value: "mysecret"
    volumeMounts:
      - name: vol
        mountPath: /tmp
