apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: secret-sidecar
  labels:
    app: myapp
spec:
  volumes:
    - name: vol
      emptyDir:
        medium: Memory
    - name: identity-server-conf
      configMap:
        name: identity-server-conf
  containers:
  - name: is-7
    image: acrasgardeomainrnd001.azurecr.io/is7.0:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 9443
    env:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    volumeMounts:
      - name: vol
        mountPath: /home/wso2carbon/wso2is-7.0.0
      - name: identity-server-conf
        mountPath: /home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
        subPath: deployment-toml
  initContainers:
  - name: secrets-manager
    image: acrasgardeomainrnd001.azurecr.io/secret-sidecar:latest
    env:
      - name: AZURE_VAULT_NAME
        value: "secretsidecar"
      - name: AZURE_SECRET_NAME
        value: "mysecret"
      - name: AZURE_CLIENT_ID
        value: "<ClientID>"
    volumeMounts:
      - name: vol
        mountPath: /home/wso2carbon/wso2is-7.0.0
